#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""@package ldm_parser
Copyright (C) 2019 University of Virginia. All rights reserved.

file      ldm7-trial-parser.py
author    Yuanlong Tan <yt4xb@virginia.edu>
version	  1.0
date      Aug. 28, 2019
LICENSE

This program is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the Free
Software Foundation; either version 2 of the License, or（at your option）
any later version.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
more details at http://www.gnu.org/copyleft/gpl.html

brief     parses log files generated by LDM7 receivers.
usage     python ldm7-trial-parser.py <logfile> <csvfile-to-write>
"""


from __future__ import division
import re
import sys
import pytz
from datetime import datetime


def parseMLDM(line):
    """Parses the product size and elapsed time received by MLDM.

    Parses the product size and elapsed receiving time consumed
    for the product (which is received by MLDM) in the given line
    of log file.

    Args:
        line: A line of the raw log file.

    Returns:
        (-1, -1, -1, -1): If no valid size or time is found.
        (prodindex, prodsize, rxtime): A tuple of product index, product size,
	receiving time and FMTP retransmitted blocks.
    """
    match = re.search(r'.*Mldm.*Received', line)
    if match:
	split_line = line.split()
	prodindex = int(split_line[9].split(",")[0])
	# col 14 is size in bytes
	size = int(split_line[14])
	# col 0 is the arrival time, col 7 is the insertion time.
	arrival_time = split_line[0]
	rxtime = float(split_line[6])
	retrans = int(split_line[11].split(",")[0])
	return (prodindex, arrival_time, size, rxtime, retrans)
    else:
	return (-1, -1, -1, -1, -1)

def parseBackstop(feedtype, line):
	"""Parses the product size and elapsed time received by the backstop.

	Parses the product size and elapsed receiving time consumed for the
	product (which is received by the backstop) in the given line of log file.

	Args:
		line: A line of the raw log file.

	Returns:
		(-1, -1, -1): If no valid size or time is found.
		(prodindex, prodsize, rxtime): A tuple of product index, product size
									   and receiving time.
	"""
	match = re.search(r'.*down7.*Inserted', line)
	if match:
		split_line = line.split()
		arrival_time = datetime.strptime(split_line[0], "%Y%m%dT%H%M%S.%fZ")
		insert_time  = datetime.strptime(split_line[6], "%Y%m%d%H%M%S.%f")
		# the last column is product index
		prodindex = int(split_line[8])
		# col 6 is size in bytes
		size = int(split_line[5])
		# col 0 is the arrival time, col 7 is the insertion time.
		# arrival_time = parse(split_line[0]).astimezone(pytz.utc).arrival_time.replace(tzinfo=None)
		rxtime = (arrival_time - insert_time).total_seconds()
		return (prodindex, size, rxtime)
	else:
		return (-1, -1, -1)


def extractLog(filename):
    """Extracts the key information from the log file.

    Args:
        filename: Filename of the log file.

    Returns:
        (complete_set, complete_dict, vset): extracted groups.
    """
    complete_set  = set()
    complete_dict = {}
    with open(filename, 'r') as logfile:
        for i, line in enumerate(logfile):
            (mprodid, arrival_time, msize, mrxtime, retrans) = parseMLDM(line)
            if mprodid >= 0:
                complete_set |= {mprodid}
                if not complete_dict.has_key(mprodid):
                    complete_dict[mprodid] = (arrival_time, msize, mrxtime, retrans)
    logfile.close()
    return (complete_set, complete_dict)


def main(logfile, csvfile):
    """Reads the raw log file and parses it.

    Reads the raw ldmd log file, parses each line and computes throughput
    and VSR over an aggregate size.

    Args:
        logfile: Filename of the log file.
        csvfile : Filename of the new file to contain output results.
    """
    w = open(csvfile, 'w+')
    pre_count = 0
    count = 0
    sizes = []
    latencies = []
    (rx_success_set, rx_success_dict) = extractLog(logfile)
    tmp_str = 'timestamp, prodindex, size (B), latency (s), retrans, per_thru (bps)' + '\n'
    w.write(tmp_str)
    for i in rx_success_set:
	if rx_success_dict[i][2] > 0:
		per_thru = rx_success_dict[i][1] * 8 / rx_success_dict[i][2]
		tmp_str = str(rx_success_dict[i][0]) + ',' + str(i) + ',' + str(rx_success_dict[i][1]) + ',' \
		+ str(rx_success_dict[i][2]) + ',' + str(rx_success_dict[i][3]) + ',' + str(per_thru) + '\n'
	else:
		pre_count += 1
		tmp_str = str(rx_success_dict[i][0]) + ',' + str(i) + ',' + str(rx_success_dict[i][1]) + ',' \
		+ str(rx_success_dict[i][2]) + ',' + str(rx_success_dict[i][3]) + ',' + '0' + '\n'
	w.write(tmp_str)
    tmp_str = str(pre_count) + '\n'
    w.write(tmp_str)
    w.close()

if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
